stages:
  - build
  - test

build:
  stage: build
  image: node
  script: 
    - echo "Start building App"
    - npm install
    - npm run build
    - echo "Build successfully!"
  artifacts:
    expire_in: 1 hour
    paths:
      - build
      - node_modules/
  tags:
    - docker

units:
  stage: test  
  image: node
  script:
    - echo "Testing App"
    - CI=true npm test
    - echo "Test successfully!"
  tags:
  - docker

tslint:
  stage: test
  image: node
  before_script:
    - export PATH=$PATH:$PWD/node_modules/.bin/
  script:
    - echo "Linting App"
    - npm run eslint
    - echo "Test successfully!"
  tags:
    - docker 

.dependabot:
  image: dependabot/dependabot-core
  variables:
    PACKAGE_MANAGER: $CI_JOB_NAME
  retry: 1
  before_script:
    - bundle install -j $(nproc) --path node_modules
  script: bundle exec ruby ./update.rb
  cache:
    paths:
      - node_modules/
  # only:
    # - schedules

npm_and_yarn:
  stage: build
  extends: .dependabot
  variables:
    DEPENDABOT_UPDATE_STRATEGY: 'bump_versions'